name: moveit
description: Time your development time!

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get: ^4.0.0-nullsafety.2
  flutter_svg: ^0.21.0-nullsafety.0
  animate_do: ^1.7.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
          
  assets:
      - assets/icons/level.svg
      - assets/icons/body.svg
      - assets/icons/level-up.svg
      - assets/notification.mp3
  